version: '3'

services:
  webserver:
    build: ./data/nginx/conf
    restart: always
    ports:
      - "80:80"
    container_name: webserver
    volumes:
      - ./data/nginx/conf/:/etc/nginx/
      - ./data/nginx/www/:/var/www/
      - ./data/certbot/www/:/var/www/certbot/
      - ./data/certbot/conf/:/etc/letsencrypt/

  certbot:
    image: certbot/certbot
    depends_on:
      - webserver
    container_name: certbot
    volumes:
      - ./data/certbot/www/:/var/www/certbot/
      - ./data/certbot/conf/:/etc/letsencrypt/
